#! /usr/bin/ruby

$: << './lib'

require 'eventmachine'
require 'second-contract'
require 'optparse'
require 'yaml'

options = {
  environment: "production"
}

OptionParser.new do |opts|
  opts.banner = "Usage: driver [options] config.yml"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on("-c", "--check", "Check syntax only") do |c|
    options[:check] = c
  end

  opts.on("-e", "--env", "Set environment type") do |e|
    options[:environment] = e
  end
end.parse!

# ARGV should have a config file now
if ARGV.length == 1
  config_file = ARGV[0]
else
  config_file = "config/game.yml"
end

config = YAML.load_file(config_file)
if config.include?(options[:environment])
  config = config[options[:environment]]
else
  puts "Unable to find #{options[:environment]} configuration in #{config_file}"
  exit 0
end

config['verbose'] = options['verbose']

if options[:check]
  SecondContract::Game.instance.config(config).compile_all
else
  ActiveRecord::Base.establish_connection(config)
  ActiveRecord::Base.connection
  
  EventMachine::run {
    SecondContract::Driver.instance.config(config).start
  }
end
